<?php

use Symfony\Component\EventDispatcher\GenericEvent;

/**
 * @file
 * Main module file for the Scalable Content module.
 */

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function scalable_content_external_content_insert(\Drupal\Core\Entity\EntityInterface $entity): void {
  \Drupal::logger('scalable_content')->info(
    'External content entity @id was inserted.',
    [
      '@id' => $entity->id(),
    ]
  );

  \Drupal::service('event_dispatcher')->dispatch(
    new GenericEvent($entity),
    'scalable_content.entity_insert'
  );
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function scalable_content_external_content_update(\Drupal\Core\Entity\EntityInterface $entity): void {
  \Drupal::logger('scalable_content')->info(
    'External content entity @id was updated.',
    [
      '@id' => $entity->id(),
    ]
  );

  \Drupal::service('event_dispatcher')->dispatch(
    new GenericEvent($entity),
    'scalable_content.entity_update'
  );
}

/**
 * Implements hook_views_data_alter().
 */
function scalable_content_views_data_alter(array &$data): void {
  if (isset($data['external_content_field_data']['category'])) {
    $data['external_content_field_data']['category']['filter']['id'] =
      'scalable_external_content_category';
  }

  // Use the custom query plugin for External Content views.
  if (isset($data['external_content_field_data']['table']['base'])) {
    $data['external_content_field_data']['table']['base']['query_id'] =
      'scalable_content_sql';
  }
}



